server:
  port: 8080

spring:
  application:
    name: ai-language-learner
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

ai:
  provider: ollama  # Options: ollama, openai, azure
  timeout: 600000
  ollama:
    base-url: http://localhost:11555
    model: gemma3

  tts:
    cuda-version: cu128

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    ch.yanick.ai.ailanguagelearner: DEBUG
    org.springframework.web: DEBUG
    reactor.netty: INFO
